### ISSUE TITLE
parity in functionality for java_image

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/rules_docker#574]
Hi everyone,
Currently there are some features of java_binary that are not easily supported with java_image.
Specifically, attributes that result in flags passed to the java wrapper script (https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L35) are not easy to convert to java_image behavior. Example: https://github.com/bazelbuild/rules_docker/pull/563

Opening up this issue to have wider conversation about how to fix.
One suggested solution in PR above: have an equivalent of the wrapper script inJava: might be expensive to maintain but would guarantee it is possible to keep behavior on par.

**Comment by ceason** [comment]
What about using the [`JAVA_TOOL_OPTIONS`](https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#tooloptions) env var? For example, with kubernetes:
```
      - name: myapp
        image: myapp
        args:
        - 'applicationArgument1'
        - 'applicationAgument2'
        env:
        - name: JAVA_TOOL_OPTS
          value: '-Xms10g -Xmx10g'
```
