### ISSUE TITLE
Create root OWNERS file

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_docker#784]
prow.k8s.io is configured to use blunderbuss to attempt to auto-assign reviewers for PRs -- https://github.com/kubernetes/test-infra/blob/master/prow/plugins.yaml#L334

At a minimu, this requires a root OWNERS file (although like inside Google this can also be further tuned in subdirs), similar to what is present in rules_k8s: https://github.com/bazelbuild/rules_k8s/blob/master/OWNERS

Can we do so here too?

```yaml
jsonPayload: {
  component:  "hook"   
  event-GUID:  "883dca20-5703-11e9-8809-32efaa964d15"   
  event-type:  "pull_request_review"   
  level:  "warning"   
  msg:  "Couldn't find/suggest approvers for each files. Unapproved: [""]"   
  org:  "bazelbuild"   
  plugin:  "approve"   
  pr:  783   
  repo:  "rules_docker"   
  review:  222917563   
  reviewer:  "alex1545"   
  url:  "https://github.com/bazelbuild/rules_docker/pull/783#pullrequestreview-222917563"   
 }
```
